spring:
  config:
    activate:
      on-profile: dev

  data:
    mongodb:
      database: ${DB_MONGODB_NAME:vocabulary-command-service}
      host: ${DB_MONGODB_HOST:mongodb}
      username: ${DB_MONGODB_USER:User}
      password: ${DB_MONGODB_PASSWORD:password}
      port: ${DB_MONGODB_PORT:27017}

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:9092}
      group-id: ${KAFKA_GROUP:vocabulary-read-service-group}

server:
  port: ${SERVER_PORT:8813}

grpc:
  server:
    port: ${GRPC_PORT:9099}
    address: 0.0.0.0
    reflectionServiceEnabled: true

logging:
  level:
    root: DEBUG
