spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://${DB_POSTGRESQL_HOST:postgres}:${DB_POSTGRESQL_PORT:5432}/${DB_POSTGRESQL_NAME:deck}
    username: ${DB_POSTGRESQL_USER:admin}
    password: ${DB_POSTGRESQL_PASSWORD:adminpassword}

    datasource:
      url: ${DATASOURCE_URL:jdbc:postgresql://postgres:5432/outbox}
      username: ${DATASOURCE_USERNAME:admin}
      password: ${DATASOURCE_PASSWORD:adminpassword}

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:9092}

server:
  port: ${SERVER_PORT:8814}

grpc:
  client:
    vocabulary-read:
      address: ${GRPC_VOCAB_READ_ADDRESS:static://vocabulary-read-service:9099}
      negotiationType: ${GRPC_VOCAB_READ_NEGOTIATION:PLAINTEXT}

logging:
  logstash:
    host: ${LOGSTASH_HOST:logstash-1}