spring.application.name=deck-service
server.port=8004

#spring.datasource.url=jdbc:
#spring.datasource.username=
#spring.datasource.password=
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=
spring.jpa.properties.hibernate.dialect=
springdoc.api-docs.path=
springdoc.swagger-ui.path=
springdoc.swagger-ui.enabled=
springdoc.api-docs.enabled=

spring.security.oauth2.resourceserver.jwt.jwk-set-uri =
spring.kafka.consumer.bootstrap-servers =
spring.kafka.consumer.group-id =
spring.kafka.consumer.auto-offset-reset =
spring.kafka.consumer.key-deserializer=
spring.kafka.consumer.value-deserializer=
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=

logging.level.org.apache.kafka=
logging.level.org.postgresql=
logging.level.org.hibernate=

vocabulary-read-service.url=
vocabulary-read-service.name=
vocabulary-read-service.path=
vocabulary-read-service.url.get-words=
vocabulary-read-service.url.get-vocabularies=