spring.application.name=deck-service
server.port=8004

spring.datasource.url=jdbc:postgresql://localhost:5432/deck
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri = http://localhost:0003/.well-known/jwks.json

spring.kafka.consumer.bootstrap-servers = 127.0.0.1:29092
spring.kafka.consumer.group-id = sentence-service-group
spring.kafka.consumer.auto-offset-reset = earliest
spring.kafka.consumer.key-deserializer = org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer = org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class = org.springframework.kafka.support.serializer.JsonDeserializer

logging.level.org.apache.kafka=INFO

logging.level.org.postgresql=INFO
logging.level.org.hibernate=INFO

vocabulary-read-service.url=http://localhost:2/api/v1/vocabulary
vocabulary-read-service.name=vocabulary-read-service
vocabulary-read-service.path=/api/v1/vocabulary
vocabulary-read-service.url.get-words=/words
vocabulary-read-service.url.get-vocabularies=/vocabularies