name: learnwords

services:
  api-gateway:
    image: ${IMAGE_NAME:-api-gateway}:${IMAGE_TAG:-dev}
    container_name: api-gateway
    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}
      SERVER_PORT: ${PORT:-8811}

      # Redis
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST:-redis}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT:-6379}
      SPRING_DATA_REDIS_PASSWORD: ${SPRING_DATA_REDIS_PASSWORD:-SuperSecret123}

      # Resource Server / JWKS
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${ISSUER_URI:-http://api-gateway:8811}
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: ${JWKS_URI:-http://api-gateway:8811/.well-known/jwks.json}
      ACCESS_TOKEN: ${ACCESS_TOKEN:-access_token}

      # Keys
      JWT_PRIVATE_KEY_LOCATION: ${JWT_PRIVATE_KEY_LOCATION:-file:/etc/keys/private_key.pem}
      JWT_PUBLIC_KEY_LOCATION: ${JWT_PUBLIC_KEY_LOCATION:-file:/etc/keys/public_key.pem}
      JWT_EXPIRE_IN: ${JWT_EXPIRE_IN:-86400000}
      KID: ${KID:-gateway-kid}

      # gRPC
      GRPC_CLIENT_AUTH_ADDRESS: ${GRPC_CLIENT_AUTH_ADDRESS:-static://user-service:9098}
      GRPC_CLIENT_AUTH_NEGOTIATIONTYPE: ${GRPC_CLIENT_AUTH_NEGOTIATIONTYPE:-PLAINTEXT}

      # Observability
      ZIPKIN_ENDPOINT: ${ZIPKIN_ENDPOINT:-http://zipkin:9411/api/v2/spans}
      TRACING_PROBABILITY: ${TRACING_PROBABILITY:-1.0}

      # Logi
      LOG_LEVEL_WEB: ${LOG_LEVEL_WEB:-INFO}
      LOG_LEVEL_HTTP_CONVERTER: ${LOG_LEVEL_HTTP_CONVERTER:-INFO}
      JAVA_OPTS: ${JAVA_OPTS:-}

    volumes:
      - ./secrets:/etc/keys:ro

    ports:
      - "${PORT:-8811}:${PORT:-8811}"

    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://api-gateway:${PORT:-8811}/actuator/health/readiness | grep -q '\"status\"\\s*:\\s*\"UP\"'"]
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 30s

    networks:
      - learnwords-net

networks:
  learnwords-net:
    external: true