pipeline {
	agent { label 'builder' }

  tools {
		jdk 'JDK24'
    	maven 'Maven'
  }

  options { timestamps() }

  parameters {
    booleanParam(name: 'SKIP_TESTS', defaultValue: true, description: 'Pominąć testy?')
  }

  environment {
    MVN_FLAGS = "${params.SKIP_TESTS ? '-DskipTests' : ''}"
  }

  stages {
    stage('Checkout api-gateway') {
			steps {
				dir('api-gateway') {
					checkout scm        }
      }
    }

    stage('Build & Install api-gateway') {
			steps {
				dir('api-gateway') {
					sh "mvn -U -B clean install ${env.MVN_FLAGS}"
        }
      }
    }
  }
}
