pipeline {
	agent { label 'builder' }

  tools {
		jdk 'JDK24'
    	maven 'Maven'
  }

  options { timestamps() }

  parameters {
    booleanParam(name: 'SKIP_TESTS', defaultValue: true, description: 'Pominąć testy?')
    string(name: 'REGISTRY', defaultValue: 'localhost:5000', description: 'Local Docker registry')
    string(name: 'IMAGE_NAME', defaultValue: 'learnwords/api-gateway', description: 'Nazwa obrazu')
    string(name: 'TAG', defaultValue: '', description: 'Tag obrazu (puste => auto)')
  }

  environment {
    MVN_FLAGS = "${params.SKIP_TESTS ? '-DskipTests' : ''}"
  }

  stages {
    stage('Checkout api-gateway') {
			steps {
				dir('api-gateway') {
					checkout scm        }
      }
    }

    stage('Build & Install api-gateway') {
			steps {
				dir('api-gateway') {
					sh "mvn -U -B clean install ${env.MVN_FLAGS}"
        }
      }
    }
        stage('Build Docker image') {
			steps {
				dir('api-gateway') {
            script {
                def tag = params.TAG?.trim() ? params.TAG.trim() : "${env.BUILD_NUMBER}"
                def image = "${env.REGISTRY}/${env.IMAGE_NAME}:${tag}"
                sh "docker build -t ${image} ."
                sh "docker push ${image}"
                echo "Pushed Docker image: ${image}"
             }
 		}
 	  }
 	}
   }
 }
