{
 "title": "KAFKA Dashboard",
 "description": "[Chinese version] Updated 2024-05-20. Based on Prometheus kafka_exporter, comprehensive Kafka resource dashboard! Includes overall Kafka resource status, producer-consumer relationships, detailed message backlog information, production and consumption rates, and per-partition backlog and consumption details. https://grafana.com/orgs/starsliao/dashboards",
 "tags": [
  "Prometheus",
  "KAFKA",
  "StarsL.cn"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(kafka_brokers,job)"
    }
   },
   {
    "name": "name",
    "label": "Name",
    "query": {
     "query": "label_values(kafka_brokers{job=~\"$job\"},name)"
    }
   },
   {
    "name": "consumer_group",
    "label": "Consumer Group",
    "query": {
     "query": "query_result(count by (consumergroup)(kafka_consumergroup_members{job=\"$job\",name=~\"$name\",consumergroup!~\"__.*\"}))"
    }
   },
   {
    "name": "topic",
    "label": "topic",
    "query": {
     "query": "label_values(kafka_consumergroup_lag_sum{job=\"$job\",name=~\"$name\",topic !~\"__.*\",consumergroup=~\"$consumer_group\"},topic)"
    }
   },
   {
    "name": "consumergroup_hide",
    "label": "consumergroup_hide",
    "query": {
     "query": "label_values(kafka_consumergroup_lag_sum{job=\"$job\", name=~\"$name\", topic!~\"__.*\", topic=~\"$topic\", consumergroup!~\"__.*\"},consumergroup)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Brokers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_brokers{job=\"$job\",name=\"$name\"}"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "stat",
   "description": "Includes topics with no consumer groups consuming them",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_topic_partitions{job=\"$job\",name=\"$name\",topic !~\"__.*\"})"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kafka_topic_partitions{job=\"$job\",name=\"$name\",topic !~\"__.*\"})"
    }
   ]
  },
  {
   "title": "Consumer Groups",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_consumergroup_members{job=\"$job\",name=\"$name\",consumergroup!~\"__.*\"})"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_members{job=\"$job\",name=\"$name\",consumergroup!~\"__.*\"})"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_replicas{job=\"$job\",name=\"$name\"})"
    }
   ]
  },
  {
   "title": "In Sync Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_in_sync_replica{job=\"$job\",name=\"$name\"})"
    }
   ]
  },
  {
   "title": "Partitions not on preferred node",
   "type": "stat",
   "description": "Partitions not on preferred node",
   "gridPos": { "h": 3, "w": 1, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_topic_partition_leader_is_preferred{job=\"$job\",name=\"$name\"}<1)"
    }
   ]
  },
  {
   "title": "Total Production per Second",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(kafka_topic_partition_current_offset{job=\"$job\",name=\"$name\",topic !~ \"__.*\"}[3m]))"
    }
   ]
  },
  {
   "title": "Total Consumption per Second",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(kafka_consumergroup_current_offset{job=\"$job\",name=~'$name'}[3m]))"
    }
   ]
  },
  {
   "title": "Current Total Lag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag_sum{job=\"$job\",name=\"$name\"})"
    }
   ]
  },
  { "title": "Consumers and Topics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Consumer Groups (linked to right Topics table)",
   "type": "table",
   "description": "- When both menu filters are set to All Consumer Groups and All Topics, this table shows the list of consumer groups associated with topics.\n- When a consumer group is selected in the menu, the right-side table will show topics consumed by that group; the current table shows consumer groups that consume the topics listed on the right.",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "kafka_consumergroup_members{job=\"$job\",name=\"$name\",consumergroup=~\"$consumergroup_hide\",consumergroup!~\"__.*\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Topics (linked to left Consumer Groups table)",
   "type": "table",
   "description": "- When both menu filters are set to All Consumer Groups and All Topics, this table shows the list of topics associated with consumer groups.\n- When a topic is selected in the menu, the left-side table will show the list of consumers that consume that topic.",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "sum by(topic) (kafka_topic_partitions{job=\"$job\",name=\"$name\",topic !~\"__.*\",topic=~\"$topic\"})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Group Lag > 100 (linked Consumer Group, Topic)",
   "type": "timeseries",
   "description": "No data indicates there are no consumer groups with backlog greater than 100.",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag_sum{job=\"$job\",name=\"$name\",consumergroup=~\"$consumer_group\",consumergroup!~\"__.*\",topic!~\"__.*\"}) by (consumergroup, topic)>100",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Topic Production per Second (linked to Topic)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_topic_partition_current_offset{job=\"$job\",name=\"$name\",topic !~ \"__.*\",topic=~\"$topic\"}[3m])) by (topic)>0",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Group Consumption per Second (linked Consumer Group, Topic)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_consumergroup_current_offset{job=\"$job\",name=~'$name',consumergroup=~\"$consumer_group\",topic=~\"$topic\",consumergroup!~\"__.*\",topic!~\"__.*\"}[3m])) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Topic view: Total consumed/s - production/s * number of consumer groups (negative = under-consumption)",
   "type": "timeseries",
   "description": "Displays the total consumption per second for each topic (topic dimension).",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(kafka_consumergroup_current_offset{job=\"$job\",name=~'$name',topic=~\"$topic\",consumergroup!~\"__.*\",topic!~\"__.*\"}[3m])) by (topic) - sum(irate(kafka_topic_partition_current_offset{job=\"$job\",name=\"$name\",topic!~\"__.*\",topic=~\"$topic\"}[3m])) by (topic) * count(kafka_consumergroup_lag_sum{job=\"$job\",name=\"$name\",consumergroup!~\"__.*\",topic!~\"__.*\",topic=~\"$topic\"}) by(topic) != 0",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer groups without associated Topics (persistent consumers need attention)",
   "type": "timeseries",
   "description": "No data indicates all consumer groups are associated with Topics",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (consumergroup,job,name) (kafka_consumergroup_members{job=\"$job\",name=\"$name\",consumergroup!~\"__.*\"}) unless sum by (consumergroup,job,name)(kafka_consumergroup_lag_sum{job=\"$job\",name=~\"$name\",consumergroup!~\"__.*\",topic!~\"__.*\"}) ",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Topics without consumer groups (persistent topics need attention)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (topic,job,name)(kafka_topic_partition_current_offset{job=\"$job\",name=~\"$name\",topic !~\"__.*\"} - kafka_topic_partition_oldest_offset{job=\"$job\",name=~\"$name\",topic !~\"__.*\"}) unless count by (topic,job,name)(kafka_consumergroup_lag_sum{job=\"$job\",name=~\"$name\",consumergroup!~\"__.*\",topic!~\"__.*\"}) ",
     "legendFormat": "{{topic}} total messages"
    },
    {
     "expr": "sum by (topic,job,name)(irate(kafka_topic_partition_current_offset{job=\"$job\",name=\"$name\",topic !~ \"__.*\"}[3m])) unless count by (topic,job,name)(kafka_consumergroup_lag_sum{job=\"$job\",name=~\"$name\",consumergroup!~\"__.*\",topic!~\"__.*\"}) ",
     "legendFormat": "{{topic}} production/s"
    }
   ]
  },
  {
   "title": "Partition view [consumer group must be specified]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumer Group [$consumer_group] partitions [Current Lag]",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_lag{job=\"$job\",name=\"$name\",consumergroup=\"$consumer_group\",topic=~\"$topic\",consumergroup!~\"__.*\",topic!~\"__.*\"}) by (consumergroup, topic,partition)",
       "legendFormat": "{{consumergroup}} (topic: {{topic}}) partition:{{partition}}"
      }
     ]
    },
    {
     "title": "Consumer Group [$consumer_group] partitions [Consumption/s]",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(kafka_consumergroup_current_offset{job=\"$job\",name=~'$name',consumergroup=\"$consumer_group\",topic=~\"$topic\",consumergroup!~\"__.*\",topic!~\"__.*\"}[3m])",
       "legendFormat": "{{consumergroup}} (topic: {{topic}}) partition:{{partition}}"
      }
     ]
    }
   ]
  }
 ]
}