pipeline {
	agent any
	  tools {
		jdk 'JDK21'
  }
  options { timestamps() }
  parameters {
		string(name: 'BRANCH', defaultValue: 'main', description: 'Git branch do zbudowania (parent + proto-shared)')
    booleanParam(name: 'SKIP_TESTS', defaultValue: true, description: 'Pominąć testy?')
    booleanParam(name: 'BUILD_PARENT', defaultValue: true, description: 'Zbudować parenta przed proto-shared?')
  }
  environment {
		CREDS_ID = 'bitbucket'
    PARENT_REPO = 'git@bitbucket.org:grzegorz5/learnwords-parent.git'
    PROTO_REPO  = 'git@bitbucket.org:grzegorz5/proto-shared.git'
    PARENT_DIR  = 'learnwords-backend/learnwords-services'
    PROTO_DIR   = 'learnwords-backend/learnwords-services/proto-shared'
    MVN_FLAGS   = "${params.SKIP_TESTS ? '-DskipTests' : ''}"
  }
  stages {
		stage('Checkout parent (for relativePath)') {
			steps {
				dir("${env.PARENT_DIR}") {
					git branch: "${params.BRANCH}", credentialsId: "${env.CREDS_ID}", url: "${env.PARENT_REPO}"
        }
      }
    }

    stage('Checkout proto-shared') {
			steps {
				dir("${env.PROTO_DIR}") {
					git branch: "${params.BRANCH}", credentialsId: "${env.CREDS_ID}", url: "${env.PROTO_REPO}"
        }
      }
    }

    stage('Build parent (optional)') {
			when { expression { return params.BUILD_PARENT } }
      steps {
				dir("${env.PARENT_DIR}") {
					sh "./mvnw -U clean install ${env.MVN_FLAGS}"
        }
      }
    }

    stage('Build & Install proto-shared') {
			steps {
				dir("${env.PROTO_DIR}") {
					sh "echo 'Wersja Javy:' && ./mvnw -version"
    sh "./mvnw -U clean install ${env.MVN_FLAGS}"
  }
}
		//	steps {
		//		dir("${env.PROTO_DIR}") {
		//			sh "./mvnw -U clean install ${env.MVN_FLAGS}"
      //  }
      //}
steps {
				dir("${env.PROTO_DIR}") {
					sh "export JAVA_HOME=\$(readlink -f \$(which java) | sed 's:/bin/java::') && ./mvnw -U clean install ${env.MVN_FLAGS}"
  }
}

    }
  }
}
