version: "3.9"

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    networks: [learnwords-net]

networks:
  learnwords-net:
    external: true
