pipeline {
	agent { label 'builder' }

  options { timestamps() }

  parameters {
    string(name: 'REGISTRY', defaultValue: 'localhost:5000', description: 'Local Docker registry')
    string(name: 'IMAGE_NAME', defaultValue: 'learnwords/deck-service', description: 'Nazwa obrazu')
    string(name: 'TAG', defaultValue: 'dev', description: 'Tag obrazu (puste => auto)')

  }

    stage('Checkout frontend') {
			steps {
				dir('frontend') {
					checkout scm        }
      }
    }

    stage('Build Docker image') {
			steps {
				dir('frontend') {
            script {
                def tag = params.TAG?.trim() ? params.TAG.trim() : "${env.BUILD_NUMBER}"
                def image = "${env.REGISTRY}/${env.IMAGE_NAME}:${tag}"
                sh "docker build -t ${image} ."
                sh "docker push ${image}"
                echo "Pushed Docker image: ${image}"
            }
		}
	  }
	}
  }
}

