spring:
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:SuperSecret123}
  config:
    activate:
      on-profile: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI:http://api-gateway:8811}
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://api-gateway:8811/.well-known/jwks.json}
          cookie-name: ${ACCESS_TOKEN:access_token}

logging:
  level:
    root: DEBUG

server:
  port: ${SERVER_PORT:8811}

jwt:
  private-key-location: ${JWT_PRIVATE_KEY_LOCATION:classpath:jwt/private_key.pem}
  public-key-location: ${JWT_PUBLIC_KEY_LOCATION:classpath:jwt/public_key.pem}
  expire-in: ${JWT_EXPIRE_IN:86400000}

grpc:
  client:
    auth:
      address: ${GRPC_CLIENT_AUTH_ADDRESS:static://user-service:9098}
      negotiationType: ${GRPC_CLIENT_AUTH_NEGOTIATIONTYPE:PLAINTEXT}