name: learnwords

services:
  deck-service:
    image: ${IMAGE_NAME:-deck-service}:${IMAGE_TAG:-dev}
    container_name: deck-service
    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE:-dev}
      SERVER_PORT: ${PORT:-8814}

      DB_POSTGRESQL_HOST: ${DB_POSTGRESQL_HOST:-postgres}
      DB_POSTGRESQL_PORT: ${DB_POSTGRESQL_PORT:-5432}
      DB_POSTGRESQL_NAME: ${DB_POSTGRESQL_NAME:-deck}
      DB_POSTGRESQL_USER: ${DB_POSTGRESQL_USER:-admin}
      DB_POSTGRESQL_PASSWORD: ${DB_POSTGRESQL_PASSWORD:-adminpassword}

      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      KAFKA_GROUP: ${KAFKA_GROUP:-deck-service-group}
      KAFKA_AUTO_OFFSET_RESET: ${KAFKA_AUTO_OFFSET_RESET:-earliest}

      GRPC_VOCAB_READ_ADDRESS: ${GRPC_VOCAB_READ_ADDRESS:-static://vocabulary-read-service:9099}
      GRPC_VOCAB_READ_NEGOTIATION: ${GRPC_VOCAB_READ_NEGOTIATION:-PLAINTEXT}

      GRPC_CLIENT_AUTH_ADDRESS: ${GRPC_CLIENT_AUTH_ADDRESS:-static://user-service:9098}
      GRPC_CLIENT_AUTH_NEGOTIATIONTYPE: ${GRPC_CLIENT_AUTH_NEGOTIATIONTYPE:-PLAINTEXT}
      GRPC_USER_RELATIONS_ADDRESS: ${GRPC_USER_RELATIONS_ADDRESS:-static://user-service:9098}
      GRPC_USER_RELATIONS_NEGOTIATION: ${GRPC_USER_RELATIONS_NEGOTIATION:-PLAINTEXT}
      GRPC_STUDENT_GROUPS_ADDRESS: ${GRPC_STUDENT_GROUPS_ADDRESS:-static://user-service:9098}
      GRPC_STUDENT_GROUPS_NEGOTIATION: ${GRPC_STUDENT_GROUPS_NEGOTIATION:-PLAINTEXT}

      LOGSTASH_HOST: ${LOGSTASH_HOST:-logstash}


      JAVA_OPTS: ${JAVA_OPTS:-}

    ports:
      - "${PORT:-8814}:${PORT:-8814}"

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://deck-service:${PORT:-8814}/actuator/health/readiness | grep -q '\"status\"\\s*:\\s*\"UP\"'"]
      interval: 10s
      timeout: 3s
      retries: 12
      start_period: 30s

    networks:
      - learnwords-net

networks:
  learnwords-net:
    external: true
