pipeline {
  agent { docker { image 'maven:3.9-eclipse-temurin-21' } }
  environment {
    APP_NAME = 'deck-service'
    IMAGE_NAME = "${APP_NAME}"
    TAG = "${env.BRANCH_NAME?.replaceAll('/','-') ?: 'dev'}"
    IMAGE = "${IMAGE_NAME}:${TAG}"
    SKIP_TESTS = 'true'
  }
  options { timestamps() }
  stages {
    stage('Checkout both repos') {
      steps {
        dir('parent') {
          git branch: 'main', url: 'git@bitbucket.org:grzegorz5/learnwords-parent.git'
        }
        dir('deck-service') {
          git branch: 'main', url: 'git@bitbucket.org:grzegorz5/deck-service.git'
        }
      }
    }
    stage('Install parent POM') {
      steps {
        dir('parent') {
          sh 'mvn -N -q -B -DskipTests install'
        }
      }
    }
    stage('Build service JAR') {
      steps {
        dir('deck-service') {
          sh './mvnw -q -B -DskipTests=${SKIP_TESTS} clean package'
          archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
        }
      }
    }
    stage('Build Docker image') {
      agent any
      steps {
        dir('deck-service') {
          sh 'docker build --pull --no-cache -t ${IMAGE} .'
        }
      }
    }
  }
}
