http {
 include mime.types;


    upstream apigateway {
        server apigateway:8080;
        server apigateway:8081;
    }

 server {
    listen 80;
    root   /usr/share/nginx/html;

    location /test2/ {
        alias /usr/share/nginx/html/test/;
    }
 }
}

events {

}




