spring.application.name=user-service

server.port=0003

# PostgreSQL configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/user_management
spring.datasource.username=admin
spring.datasource.password=adminpassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
springdoc.api-docs.path=/api-docs
# Swagger configuration
springdoc.swagger-ui.path=/user-api-docs-ui.html
jwt.secret = X2v9L4n7Pq8Rw5TfZx1Kc3BmNh6Ye0Tu
jwt.expire-in = 86400000
