server:
  port: ${SERVER_PORT:8812}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:user-service}

  datasource:
    url: jdbc:postgresql://${DB_POSTGRESQL_HOST:localhost}:${DB_POSTGRESQL_PORT:5432}/${DB_POSTGRESQL_NAME:user_management}
    username: ${DATASOURCE_USERNAME:admin}
    password: ${DATASOURCE_PASSWORD:adminpassword}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: false

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
