pipeline {
	agent { label 'builder' }

  tools {
		jdk 'JDK24'
    maven 'Maven'
  }

  options { timestamps() }

  parameters {
		string(name: 'PARENT_BRANCH', defaultValue: 'main', description: 'Git branch dla parent')
    string(name: 'COMMON_BRANCH', defaultValue: 'gRCP', description: 'Git branch dla common')
    booleanParam(name: 'SKIP_TESTS', defaultValue: true, description: 'Pominąć testy?')
    booleanParam(name: 'BUILD_PARENT', defaultValue: true, description: 'Zbudować parenta przed common?')
  }

  environment {
		CREDS_ID   = 'bitbucket'
    PARENT_REPO= 'git@bitbucket.org:grzegorz5/learnwords-parent.git' // POM-only parent
    COMMON_REPO= 'git@bitbucket.org:grzegorz5/common.git'
  }

  stages {
		stage('Checkout parent (for relativePath)') {
			steps {
				dir('parent') {
					git branch: params.PARENT_BRANCH, credentialsId: env.CREDS_ID, url: env.PARENT_REPO
        }
      }
    }

    stage('Checkout common') {
			steps {
				dir('common') {
					git branch: params.COMMON_BRANCH, credentialsId: env.CREDS_ID, url: env.COMMON_REPO
        }
      }
    }

    stage('Build parent (optional)') {
			when { expression { return params.BUILD_PARENT } }
      steps {
				dir('parent') {
					// tylko POM (non-recursive) trafia do ~/.m2
          sh 'mvn -U -B -N -f pom.xml install'
        }
      }
    }

    stage('Build & Install common') {
			steps {
				dir('common') {
					script {
						def flags = params.SKIP_TESTS ? '-DskipTests' : ''
            sh "mvn -U -B clean install ${flags}"
          }
        }
      }
    }
  }
}
