pipeline {
	agent { label 'builder' }

  tools {
		jdk 'JDK24'
    	maven 'Maven'
  }

  options { timestamps() }

  parameters {
	string(name: 'PARENT_BRANCH', defaultValue: 'main', description: 'Git branch dla parent')
	booleanParam(name: 'BUILD_PARENT', defaultValue: true, description: 'Zbudować parent?')
    booleanParam(name: 'SKIP_TESTS', defaultValue: true, description: 'Pominąć testy?')
  }

  environment {
	CREDS_ID   = 'bitbucket'
    PARENT_REPO= 'git@bitbucket.org:grzegorz5/learnwords-parent.git'
    MVN_FLAGS = "${params.SKIP_TESTS ? '-DskipTests' : ''}"
  }

  stages {
		stage('Checkout parent') {
			steps {
				dir('parent') {
					git branch: params.PARENT_BRANCH, credentialsId: env.CREDS_ID, url: env.PARENT_REPO
        }
      }
    }

    stage('Checkout common') {
			steps {
				dir('common') {
					checkout scm        }
      }
    }

    stage('Build parent (optional)') {
			when { expression { return params.BUILD_PARENT } }
      steps {
				dir('parent') {
          sh 'mvn -U -B -N -f pom.xml install'
        }
      }
    }

    stage('Build & Install common') {
			steps {
				dir('common') {
					sh "mvn -U -B clean install ${env.MVN_FLAGS}"
        }
      }
    }
  }
}
