pipeline {
	agent { label 'builder' }
   tools {
		jdk 'JDK24'
		maven 'Maven'
  }
  options { timestamps() }
  parameters {
		string(name: 'PARENT_BRANCH', defaultValue: 'main', description: 'Git branch dla parent')
    string(name: 'COMMON_BRANCH', defaultValue: 'gRCP', description: 'Git branch dla common')
    booleanParam(name: 'SKIP_TESTS', defaultValue: true, description: 'Pominąć testy?')
    booleanParam(name: 'BUILD_PARENT', defaultValue: true, description: 'Zbudować parenta przed common?')
  }
  environment {
		CREDS_ID = 'bitbucket'
    PARENT_REPO = 'git@bitbucket.org:grzegorz5/learnwords-parent.git'
    COMMON_REPO  = 'git@bitbucket.org:grzegorz5/common.git'
    PARENT_DIR  = 'learnwords-backend/learnwords-services'
    COMMON_DIR   = 'learnwords-backend/learnwords-services/common'
    MVN_FLAGS   = "${params.SKIP_TESTS ? '-DskipTests' : ''}"
  }
  stages {
		stage('Checkout parent (for relativePath)') {
			steps {
				dir("${env.PARENT_DIR}") {
					git branch: "${params.PARENT_BRANCH}", credentialsId: "${env.CREDS_ID}", url: "${env.PARENT_REPO}"
        }
      }
    }

    stage('Checkout common') {
			steps {
				dir("${env.COMMON_DIR}") {
					git branch: "${params.COMMON_BRANCH}", credentialsId: "${env.CREDS_ID}", url: "${env.COMMON_REPO}"
        }
      }
    }

    stage('Build parent (optional)') {
			when { expression { return params.BUILD_PARENT } }
      steps {
				dir("${env.PARENT_DIR}") {
					sh "./mvn -U clean install ${env.MVN_FLAGS}"
        }
      }
    }

    stage('Build & Install common') {
			steps {
				dir("${env.COMMON_DIR}") {
					sh "./mvn -U clean install ${env.MVN_FLAGS}"
        }
      }
    }
  }
}
