name: learnwords

services:
  user-service:
    image: ${IMAGE_NAME:-user-service}:${IMAGE_TAG:-dev}
    container_name: user-service
    environment:
      SPRING_PROFILES_ACTIVE: ${PROFILE:-dev}

      SERVER_PORT: ${PORT:-8812}
      GRPC_PORT: ${GRPC_PORT:-9098}

      DATASOURCE_URL: ${DATASOURCE_URL:-jdbc:postgresql://postgres:5432/user_management}
      DB_POSTGRESQL_USER: ${DB_POSTGRESQL_USER:-admin}
      DB_POSTGRESQL_PASSWORD: ${DB_POSTGRESQL_PASSWORD:-adminpassword}

    ports:
      - "${PORT:-8812}:${PORT:-8812}"
      - "${GRPC_PORT:-9098}:${GRPC_PORT:-9098}"
    networks: [learnwords-net]

networks:
  learnwords-net:
    external: true
