services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    networks: [learnwords-net]
  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.4.2
    container_name: nginx-exporter
    command:
      - "--nginx.scrape-uri=http://nginx:80/stub_status"
    ports:
      - "9113:9113"
    networks: [learnwords-net]

networks:
  learnwords-net:
    external: true