services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: outbox
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [learnwords-net]

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8081:80"
    depends_on: [postgres]
    networks: [learnwords-net]

  mongodb:
    image: mongo:8.0.9
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    volumes:
      - mongodb-data:/data/db
    networks: [learnwords-net]

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: mongo-express
    ports:
      - "8092:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://admin:secretpassword@mongodb:27017/?authSource=admin"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: secretpassword
    depends_on: [mongodb]
    networks: [learnwords-net]

  redis:
    image: redis:8.2.2
    container_name: redis
    command: [
      "redis-server",
      "--requirepass", "SuperSecret123",
      "--appendonly", "yes"
    ]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks: [learnwords-net]

  redisinsight:
    image: redis/redisinsight:2.70
    container_name: redisinsight
    ports:
      - "5540:5540"
    networks: [learnwords-net]

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    container_name: clickhouse
    ports:
      - "8123:8123"   # HTTP
      - "9000:9000"   # Native
    environment:
      - CLICKHOUSE_DB=learnwords
      - CLICKHOUSE_USER=wawrzen
      - CLICKHOUSE_PASSWORD=Ubuntu98
      - TZ=Europe/Warsaw
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks: [learnwords-net]
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  tabix:
    image: spoonest/clickhouse-tabix-web-client
    container_name: clickhouse-tabix
    ports:
      - "8080:80"
    networks: [learnwords-net]
    depends_on: [clickhouse]


volumes:
  pgdata:
  mongodb-data:
  redis_data:
  clickhouse_data:

networks:
  learnwords-net:
    external: true