name: learnwords
services:
  prometheus:
    image: prom/prometheus:v3.7.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks: [learnwords-net]

  grafana:
    image: grafana/grafana:12.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks: [learnwords-net]

  zipkin:
    image: openzipkin/zipkin:3.5.1
    container_name: zipkin
    ports:
      - "9411:9411"
    networks: [learnwords-net]
    environment:
      - STORAGE_TYPE=mem

networks:
  learnwords-net:
    external: true
