pipeline {
	agent any

    stages {
		stage('Checkout') {
			steps {
				checkout scm
            }
        }

        stage('Create Network') {
			steps {
				sh 'docker network create learnwords-net 2>/dev/null || true'
            }
        }

        stage('Start Databases') {
			steps {

					sh 'docker compose -f docker-compose.db.yml up -d'

            }
        }
    }

    post {
		success {
			echo 'Bazy danych zostały pomyślnie uruchomione'
        }
        failure {
			echo 'Wystąpił błąd podczas uruchamiania baz danych'
        }
    }
}
