services:
  mongodb:
    image: mongo:8.0.9
    container_name: LearnWorldsMongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secretpassword
    volumes:
      - mongodb-data:/data/db
    networks:
      shared_network:
        ipv4_address: 192.168.23.10

  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: LearnWorldsMongo-Express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: "mongodb://admin:secretpassword@mongodb:27017"
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: secretpassword
    depends_on:
      - mongodb
    networks:
      shared_network:
        ipv4_address: 192.168.23.11

volumes:
  mongodb-data:
    driver: local

networks:
  shared_network:
    external: true
