spring:
  application:
    name: koog-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://192.168.23.9:5432/koog
    username: admin
    password: adminpassword
  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

  kafka:
    producer:
      bootstrap-servers: 192.168.23.9:9094
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      properties:
        spring.json.add.type.headers: false

    consumer:
      bootstrap-servers: 192.168.23.9:9094
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"

server:
  port: 7777

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1
    export:
      zipkin:
        endpoint: http://192.168.23.9:9411/api/v2/spans

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

# Konfiguracja OpenAI
openai:
    api-key:
# Konfiguracja AI
ai:
  sentence:
    model: gpt-5-mini
    temperature: 0.7
    prompt-version: 1
